with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
filename: "{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}"
packages:
  github.com/clevertechware/gerer-ses-jobs-asynchrones-avec-postgresql/internal/handler/web:
    interfaces:
      JobRepository:
  github.com/clevertechware/gerer-ses-jobs-asynchrones-avec-postgresql/internal/handler/worker:
    interfaces:
      JobRepository:
