with-expecter: true
exported: true
disable-func-mocks: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
filename: "{{.InterfaceName | snakecase}}.go"
mockname: "{{.InterfaceName | camelcase}}"
packages:
  github.com/clevertechware/gerer-ses-jobs-asynchrones-avec-postgresql:
    config:
      all: true
      recursive: true
      dir: '{{.InterfaceDir}}/mocks'

