// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/clevertechware/gerer-ses-jobs-asynchrones-avec-postgresql/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// JobRepository is an autogenerated mock type for the jobRepository type
type JobRepository struct {
	mock.Mock
}

type JobRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *JobRepository) EXPECT() *JobRepository_Expecter {
	return &JobRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, tenantID, jobType, config
func (_m *JobRepository) Create(ctx context.Context, tenantID string, jobType domain.JobType, config interface{}) (*domain.Job, error) {
	ret := _m.Called(ctx, tenantID, jobType, config)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.JobType, interface{}) (*domain.Job, error)); ok {
		return rf(ctx, tenantID, jobType, config)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.JobType, interface{}) *domain.Job); ok {
		r0 = rf(ctx, tenantID, jobType, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.JobType, interface{}) error); ok {
		r1 = rf(ctx, tenantID, jobType, config)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JobRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type JobRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - jobType domain.JobType
//   - config interface{}
func (_e *JobRepository_Expecter) Create(ctx interface{}, tenantID interface{}, jobType interface{}, config interface{}) *JobRepository_Create_Call {
	return &JobRepository_Create_Call{Call: _e.mock.On("Create", ctx, tenantID, jobType, config)}
}

func (_c *JobRepository_Create_Call) Run(run func(ctx context.Context, tenantID string, jobType domain.JobType, config interface{})) *JobRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.JobType), args[3].(interface{}))
	})
	return _c
}

func (_c *JobRepository_Create_Call) Return(_a0 *domain.Job, _a1 error) *JobRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *JobRepository_Create_Call) RunAndReturn(run func(context.Context, string, domain.JobType, interface{}) (*domain.Job, error)) *JobRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *JobRepository) GetByID(ctx context.Context, id int64) (*domain.Job, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Job, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Job); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JobRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type JobRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *JobRepository_Expecter) GetByID(ctx interface{}, id interface{}) *JobRepository_GetByID_Call {
	return &JobRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *JobRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *JobRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *JobRepository_GetByID_Call) Return(_a0 *domain.Job, _a1 error) *JobRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *JobRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*domain.Job, error)) *JobRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobsByStatus provides a mock function with given fields: ctx, status, limit
func (_m *JobRepository) GetJobsByStatus(ctx context.Context, status domain.JobStatus, limit int) ([]*domain.Job, error) {
	ret := _m.Called(ctx, status, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetJobsByStatus")
	}

	var r0 []*domain.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.JobStatus, int) ([]*domain.Job, error)); ok {
		return rf(ctx, status, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.JobStatus, int) []*domain.Job); ok {
		r0 = rf(ctx, status, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.JobStatus, int) error); ok {
		r1 = rf(ctx, status, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JobRepository_GetJobsByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobsByStatus'
type JobRepository_GetJobsByStatus_Call struct {
	*mock.Call
}

// GetJobsByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status domain.JobStatus
//   - limit int
func (_e *JobRepository_Expecter) GetJobsByStatus(ctx interface{}, status interface{}, limit interface{}) *JobRepository_GetJobsByStatus_Call {
	return &JobRepository_GetJobsByStatus_Call{Call: _e.mock.On("GetJobsByStatus", ctx, status, limit)}
}

func (_c *JobRepository_GetJobsByStatus_Call) Run(run func(ctx context.Context, status domain.JobStatus, limit int)) *JobRepository_GetJobsByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.JobStatus), args[2].(int))
	})
	return _c
}

func (_c *JobRepository_GetJobsByStatus_Call) Return(_a0 []*domain.Job, _a1 error) *JobRepository_GetJobsByStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *JobRepository_GetJobsByStatus_Call) RunAndReturn(run func(context.Context, domain.JobStatus, int) ([]*domain.Job, error)) *JobRepository_GetJobsByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueueStats provides a mock function with given fields: ctx
func (_m *JobRepository) GetQueueStats(ctx context.Context) (*domain.QueueStats, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetQueueStats")
	}

	var r0 *domain.QueueStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.QueueStats, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.QueueStats); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.QueueStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JobRepository_GetQueueStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueueStats'
type JobRepository_GetQueueStats_Call struct {
	*mock.Call
}

// GetQueueStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *JobRepository_Expecter) GetQueueStats(ctx interface{}) *JobRepository_GetQueueStats_Call {
	return &JobRepository_GetQueueStats_Call{Call: _e.mock.On("GetQueueStats", ctx)}
}

func (_c *JobRepository_GetQueueStats_Call) Run(run func(ctx context.Context)) *JobRepository_GetQueueStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *JobRepository_GetQueueStats_Call) Return(_a0 *domain.QueueStats, _a1 error) *JobRepository_GetQueueStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *JobRepository_GetQueueStats_Call) RunAndReturn(run func(context.Context) (*domain.QueueStats, error)) *JobRepository_GetQueueStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewJobRepository creates a new instance of JobRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobRepository {
	mock := &JobRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
