// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/clevertechware/gerer-ses-jobs-asynchrones-avec-postgresql/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// JobRepository is an autogenerated mock type for the JobRepository type
type JobRepository struct {
	mock.Mock
}

type JobRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *JobRepository) EXPECT() *JobRepository_Expecter {
	return &JobRepository_Expecter{mock: &_m.Mock}
}

// Dequeue provides a mock function with given fields: ctx, batchSize
func (_m *JobRepository) Dequeue(ctx context.Context, batchSize int) ([]*domain.Job, error) {
	ret := _m.Called(ctx, batchSize)

	if len(ret) == 0 {
		panic("no return value specified for Dequeue")
	}

	var r0 []*domain.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*domain.Job, error)); ok {
		return rf(ctx, batchSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*domain.Job); ok {
		r0 = rf(ctx, batchSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, batchSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JobRepository_Dequeue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dequeue'
type JobRepository_Dequeue_Call struct {
	*mock.Call
}

// Dequeue is a helper method to define mock.On call
//   - ctx context.Context
//   - batchSize int
func (_e *JobRepository_Expecter) Dequeue(ctx interface{}, batchSize interface{}) *JobRepository_Dequeue_Call {
	return &JobRepository_Dequeue_Call{Call: _e.mock.On("Dequeue", ctx, batchSize)}
}

func (_c *JobRepository_Dequeue_Call) Run(run func(ctx context.Context, batchSize int)) *JobRepository_Dequeue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *JobRepository_Dequeue_Call) Return(_a0 []*domain.Job, _a1 error) *JobRepository_Dequeue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *JobRepository_Dequeue_Call) RunAndReturn(run func(context.Context, int) ([]*domain.Job, error)) *JobRepository_Dequeue_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status, result, errMsg, durationMs
func (_m *JobRepository) UpdateStatus(ctx context.Context, id int64, status domain.JobStatus, result interface{}, errMsg *string, durationMs *int64) error {
	ret := _m.Called(ctx, id, status, result, errMsg, durationMs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.JobStatus, interface{}, *string, *int64) error); ok {
		r0 = rf(ctx, id, status, result, errMsg, durationMs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// JobRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type JobRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - status domain.JobStatus
//   - result interface{}
//   - errMsg *string
//   - durationMs *int64
func (_e *JobRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}, result interface{}, errMsg interface{}, durationMs interface{}) *JobRepository_UpdateStatus_Call {
	return &JobRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status, result, errMsg, durationMs)}
}

func (_c *JobRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id int64, status domain.JobStatus, result interface{}, errMsg *string, durationMs *int64)) *JobRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.JobStatus), args[3].(interface{}), args[4].(*string), args[5].(*int64))
	})
	return _c
}

func (_c *JobRepository_UpdateStatus_Call) Return(_a0 error) *JobRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *JobRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, int64, domain.JobStatus, interface{}, *string, *int64) error) *JobRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateToPending provides a mock function with given fields: ctx, id, runAfter, errorMsg
func (_m *JobRepository) UpdateToPending(ctx context.Context, id int64, runAfter *string, errorMsg *string) error {
	ret := _m.Called(ctx, id, runAfter, errorMsg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateToPending")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *string, *string) error); ok {
		r0 = rf(ctx, id, runAfter, errorMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// JobRepository_UpdateToPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateToPending'
type JobRepository_UpdateToPending_Call struct {
	*mock.Call
}

// UpdateToPending is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - runAfter *string
//   - errorMsg *string
func (_e *JobRepository_Expecter) UpdateToPending(ctx interface{}, id interface{}, runAfter interface{}, errorMsg interface{}) *JobRepository_UpdateToPending_Call {
	return &JobRepository_UpdateToPending_Call{Call: _e.mock.On("UpdateToPending", ctx, id, runAfter, errorMsg)}
}

func (_c *JobRepository_UpdateToPending_Call) Run(run func(ctx context.Context, id int64, runAfter *string, errorMsg *string)) *JobRepository_UpdateToPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*string), args[3].(*string))
	})
	return _c
}

func (_c *JobRepository_UpdateToPending_Call) Return(_a0 error) *JobRepository_UpdateToPending_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *JobRepository_UpdateToPending_Call) RunAndReturn(run func(context.Context, int64, *string, *string) error) *JobRepository_UpdateToPending_Call {
	_c.Call.Return(run)
	return _c
}

// NewJobRepository creates a new instance of JobRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobRepository {
	mock := &JobRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
