// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	pgconn "github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// AdvancedTransactionalPGClient is an autogenerated mock type for the AdvancedTransactionalPGClient type
type AdvancedTransactionalPGClient struct {
	mock.Mock
}

type AdvancedTransactionalPGClient_Expecter struct {
	mock *mock.Mock
}

func (_m *AdvancedTransactionalPGClient) EXPECT() *AdvancedTransactionalPGClient_Expecter {
	return &AdvancedTransactionalPGClient_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with given fields: ctx
func (_m *AdvancedTransactionalPGClient) Begin(ctx context.Context) (pgx.Tx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 pgx.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (pgx.Tx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) pgx.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdvancedTransactionalPGClient_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type AdvancedTransactionalPGClient_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AdvancedTransactionalPGClient_Expecter) Begin(ctx interface{}) *AdvancedTransactionalPGClient_Begin_Call {
	return &AdvancedTransactionalPGClient_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *AdvancedTransactionalPGClient_Begin_Call) Run(run func(ctx context.Context)) *AdvancedTransactionalPGClient_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AdvancedTransactionalPGClient_Begin_Call) Return(_a0 pgx.Tx, _a1 error) *AdvancedTransactionalPGClient_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdvancedTransactionalPGClient_Begin_Call) RunAndReturn(run func(context.Context) (pgx.Tx, error)) *AdvancedTransactionalPGClient_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// BeginTx provides a mock function with given fields: ctx, opts
func (_m *AdvancedTransactionalPGClient) BeginTx(ctx context.Context, opts pgx.TxOptions) (pgx.Tx, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 pgx.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) (pgx.Tx, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) pgx.Tx); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.TxOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdvancedTransactionalPGClient_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type AdvancedTransactionalPGClient_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - opts pgx.TxOptions
func (_e *AdvancedTransactionalPGClient_Expecter) BeginTx(ctx interface{}, opts interface{}) *AdvancedTransactionalPGClient_BeginTx_Call {
	return &AdvancedTransactionalPGClient_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, opts)}
}

func (_c *AdvancedTransactionalPGClient_BeginTx_Call) Run(run func(ctx context.Context, opts pgx.TxOptions)) *AdvancedTransactionalPGClient_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.TxOptions))
	})
	return _c
}

func (_c *AdvancedTransactionalPGClient_BeginTx_Call) Return(_a0 pgx.Tx, _a1 error) *AdvancedTransactionalPGClient_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdvancedTransactionalPGClient_BeginTx_Call) RunAndReturn(run func(context.Context, pgx.TxOptions) (pgx.Tx, error)) *AdvancedTransactionalPGClient_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function with given fields: ctx, sql, args
func (_m *AdvancedTransactionalPGClient) Exec(ctx context.Context, sql string, args ...interface{}) (pgconn.CommandTag, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, sql)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (pgconn.CommandTag, error)); ok {
		return rf(ctx, sql, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgconn.CommandTag); ok {
		r0 = rf(ctx, sql, args...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdvancedTransactionalPGClient_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type AdvancedTransactionalPGClient_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...interface{}
func (_e *AdvancedTransactionalPGClient_Expecter) Exec(ctx interface{}, sql interface{}, args ...interface{}) *AdvancedTransactionalPGClient_Exec_Call {
	return &AdvancedTransactionalPGClient_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *AdvancedTransactionalPGClient_Exec_Call) Run(run func(ctx context.Context, sql string, args ...interface{})) *AdvancedTransactionalPGClient_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *AdvancedTransactionalPGClient_Exec_Call) Return(_a0 pgconn.CommandTag, _a1 error) *AdvancedTransactionalPGClient_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdvancedTransactionalPGClient_Exec_Call) RunAndReturn(run func(context.Context, string, ...interface{}) (pgconn.CommandTag, error)) *AdvancedTransactionalPGClient_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: ctx, sql, args
func (_m *AdvancedTransactionalPGClient) Query(ctx context.Context, sql string, args ...interface{}) (pgx.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, sql)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 pgx.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (pgx.Rows, error)); ok {
		return rf(ctx, sql, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgx.Rows); ok {
		r0 = rf(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdvancedTransactionalPGClient_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type AdvancedTransactionalPGClient_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...interface{}
func (_e *AdvancedTransactionalPGClient_Expecter) Query(ctx interface{}, sql interface{}, args ...interface{}) *AdvancedTransactionalPGClient_Query_Call {
	return &AdvancedTransactionalPGClient_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *AdvancedTransactionalPGClient_Query_Call) Run(run func(ctx context.Context, sql string, args ...interface{})) *AdvancedTransactionalPGClient_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *AdvancedTransactionalPGClient_Query_Call) Return(_a0 pgx.Rows, _a1 error) *AdvancedTransactionalPGClient_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdvancedTransactionalPGClient_Query_Call) RunAndReturn(run func(context.Context, string, ...interface{}) (pgx.Rows, error)) *AdvancedTransactionalPGClient_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function with given fields: ctx, sql, args
func (_m *AdvancedTransactionalPGClient) QueryRow(ctx context.Context, sql string, args ...interface{}) pgx.Row {
	var _ca []interface{}
	_ca = append(_ca, ctx, sql)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 pgx.Row
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgx.Row); ok {
		r0 = rf(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}

	return r0
}

// AdvancedTransactionalPGClient_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type AdvancedTransactionalPGClient_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...interface{}
func (_e *AdvancedTransactionalPGClient_Expecter) QueryRow(ctx interface{}, sql interface{}, args ...interface{}) *AdvancedTransactionalPGClient_QueryRow_Call {
	return &AdvancedTransactionalPGClient_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *AdvancedTransactionalPGClient_QueryRow_Call) Run(run func(ctx context.Context, sql string, args ...interface{})) *AdvancedTransactionalPGClient_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *AdvancedTransactionalPGClient_QueryRow_Call) Return(_a0 pgx.Row) *AdvancedTransactionalPGClient_QueryRow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AdvancedTransactionalPGClient_QueryRow_Call) RunAndReturn(run func(context.Context, string, ...interface{}) pgx.Row) *AdvancedTransactionalPGClient_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// NewAdvancedTransactionalPGClient creates a new instance of AdvancedTransactionalPGClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdvancedTransactionalPGClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdvancedTransactionalPGClient {
	mock := &AdvancedTransactionalPGClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
